# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "br-cnpj"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bruno Coimbra"]
  s.date = "2013-01-17"
  s.description = "Lib implemented in C that calculates and validates CNPJ."
  s.email = "bbcoimbra@gmail.com"
  s.extensions = ["ext/CNPJ/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown",
    "TODO"
  ]
  s.files = [
    "ext/CNPJ/cnpj.c",
    "ext/CNPJ/cnpj.h",
    "ext/CNPJ/extconf.rb",
    "ext/CNPJ/ruby_cnpj.c",
    "lib/br/cnpj.rb"
  ]
  s.homepage = "http://github.com/bbcoimbra/br-cnpj"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Calcules and validates given CNPJ"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 1.4"])
      s.add_development_dependency(%q<rake-compiler>, ["~> 0.7"])
      s.add_development_dependency(%q<rspec>, ["~> 1.3"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<jeweler>, ["~> 1.4"])
      s.add_dependency(%q<rake-compiler>, ["~> 0.7"])
      s.add_dependency(%q<rspec>, ["~> 1.3"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 1.4"])
    s.add_dependency(%q<rake-compiler>, ["~> 0.7"])
    s.add_dependency(%q<rspec>, ["~> 1.3"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

