# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: br-cnpj 1.0.1 ruby lib
# stub: ext/CNPJ/extconf.rb

Gem::Specification.new do |s|
  s.name = "br-cnpj".freeze
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Bruno Coimbra".freeze]
  s.date = "2024-02-27"
  s.description = "Lib implemented in C that calculates and validates CNPJ.".freeze
  s.email = "bbcoimbra@gmail.com".freeze
  s.extensions = ["ext/CNPJ/extconf.rb".freeze]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown",
    "TODO"
  ]
  s.files = [
    "ext/CNPJ/cnpj.c",
    "ext/CNPJ/cnpj.h",
    "ext/CNPJ/extconf.rb",
    "ext/CNPJ/ruby_cnpj.c",
    "lib/br/cnpj.rb"
  ]
  s.homepage = "http://github.com/bbcoimbra/br-cnpj".freeze
  s.rubygems_version = "3.1.6".freeze
  s.summary = "Calcules and validates given CNPJ".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.2"])
    s.add_development_dependency(%q<rake-compiler>.freeze, ["~> 1.2"])
    s.add_development_dependency(%q<rspec>.freeze, ["~> 3.13"])
    s.add_development_dependency(%q<rspec>.freeze, [">= 1.2.9"])
  else
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.2"])
    s.add_dependency(%q<rake-compiler>.freeze, ["~> 1.2"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.13"])
    s.add_dependency(%q<rspec>.freeze, [">= 1.2.9"])
  end
end

